import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

import jardin from "./@jardin/page";
import sirayane from "./@sirayane/page";

import { siteinfo } from "@/constants"

const myFont = localFont({ src: "../../public/Branch/Branch.otf"})
const quicksand = Quicksand({ subsets: ["latin"] });





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const templateComponents = {
  jardin: jardin,
  sirayane: sirayane,
  // Add more templates as needed
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  
const template = siteinfo.pTemplate;
const TemplateComponent = templateComponents[template];


  return (
    <html lang="en">
      <head>
      <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css" rel="stylesheet" />
      <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet"/>

      </head>
      <body className={myFont.className}>

{/* {children} */}
      {TemplateComponent ? <TemplateComponent /> : null}

      <script src="../path/to/flowbite/dist/flowbite.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>
      <script src="../path/to/flowbite/dist/datepicker.js"></script>
      <script src="../path/to/flatpickr.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/datepicker.min.js"></script>
      
      </body>
    </html>
  );
}
